// <auto-generated />
using System;
using Animeland.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Animeland.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250403211143_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Animeland.Domain.Entities.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalEpisodes")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeasons")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Animes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImageUrl = "https://static.wikia.nocookie.net/shingeki-no-kyojin/images/5/53/Primera_temporada_%28parte_1%29.png/revision/latest?cb=20181015211526&path-prefix=es",
                            CreatedAt = new DateTime(2025, 4, 3, 22, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Humans fight for survival against man-eating Titans.",
                            GenreId = 1,
                            ReleaseDate = new DateTime(2013, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Finished",
                            Title = "Attack on Titan",
                            TotalEpisodes = 87,
                            TotalSeasons = 4,
                            UpdateAt = new DateTime(2025, 4, 3, 22, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CoverImageUrl = "https://image.api.playstation.com/vulcan/ap/rnd/202309/2817/001971fa2fc21d37b7c0d3e9cb45b2a651252d455e90a764.png",
                            CreatedAt = new DateTime(2025, 4, 3, 22, 30, 0, 0, DateTimeKind.Utc),
                            Description = "A high school student joins a secret organization to fight curses.",
                            GenreId = 1,
                            ReleaseDate = new DateTime(2020, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "OnAir",
                            Title = "Jujutsu Kaisen",
                            TotalEpisodes = 47,
                            TotalSeasons = 2,
                            UpdateAt = new DateTime(2025, 4, 3, 22, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Animeland.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 3, 22, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Shonen",
                            UpdateAt = new DateTime(2025, 4, 3, 22, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 3, 22, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Seinen",
                            UpdateAt = new DateTime(2025, 4, 3, 22, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 4, 3, 22, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Shojo",
                            UpdateAt = new DateTime(2025, 4, 3, 22, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Animeland.Domain.Entities.Anime", b =>
                {
                    b.HasOne("Animeland.Domain.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
